import { createSlice } from '@reduxjs/toolkit'
import {
    initialState,
    initTicket,
    fetchDraw,
    setDraw,
    setDrawMapByDate,
    setDrawingConfig,
    setTicketPriceDefault,
    removeDrawSelected,
    setDrawSelected,
    setDrawSelectedAll,
    removeDrawSelectedAll,
    setDrawSelectedList,
    initNumbers,
    setNumbers,
    initSpots,
    setSpots,
    setSpotSelected,
    setSpotDefault,
    setTicketOrder,
    resetTicketOrderNumber,
    setTicketSessionSelected,
    resetTicketSession,
    randomNumberTicket,
    updateTicketOrderNumber,
    addTicket,
    removeTicket,
    clearNumberTicket,
    setTicketSession,
    updateSessionItem,
    removeSessionItem,
    clearNumberSessionItem,
    mergeTicketOrderFromSession,
    fetchConfig,
    getConfig,
    setNumberChoiceModal,
    createOrder,
    createOrderLoading
} from './reducers'

export const KEY_REDUCER_SAGA = '@keno/game'

const kenoGameSlice = createSlice({
    name: KEY_REDUCER_SAGA,
    initialState,
    reducers: {
        onInitTicket: initTicket,
        onFetchDraw: fetchDraw,
        onSetDraw: setDraw,
        onSetDrawMapByDate: setDrawMapByDate,
        onSetDrawingConfig: setDrawingConfig,
        onSetTicketPriceDefault: setTicketPriceDefault,
        onRemoveDrawSelected: removeDrawSelected,
        onSetDrawSelected: setDrawSelected,
        onSetDrawSelectedAll: setDrawSelectedAll,
        onRemoveDrawSelectedAll: removeDrawSelectedAll,
        onSetDrawSelectedList: setDrawSelectedList,
        onInitNumbers: initNumbers,
        onSetNumbers: setNumbers,
        onInitSpots: initSpots,
        onSetSpots: setSpots,
        onSetSpotSelected: setSpotSelected,
        onSetSpotDefault: setSpotDefault,
        onSetTicketOrder: setTicketOrder,
        onResetTicketOrderNumber: resetTicketOrderNumber,
        onSetTicketSessionSelected: setTicketSessionSelected,
        onResetTicketSession: resetTicketSession,
        onRandomNumberTicket: randomNumberTicket,
        onUpdateTicketOrderNumber: updateTicketOrderNumber,
        onAddTicket: addTicket,
        onRemoveTicket: removeTicket,
        onClearNumberTicket: clearNumberTicket,

        onSetTicketSession: setTicketSession,
        onUpdateSessionItem: updateSessionItem,
        onRemoveSessionItem: removeSessionItem,
        onClearNumberSessionItem: clearNumberSessionItem,
        onMergeTicketOrderFromSession: mergeTicketOrderFromSession,

        onFetchConfig: fetchConfig,
        onGetConfig: getConfig,

        onSetNumberChoiceModal: setNumberChoiceModal,
        onCreateOrder: createOrder,
        onCreateOrderLoading: createOrderLoading
    }
})

export const {
    onInitTicket,
    onFetchDraw,
    onSetDraw,
    onRemoveDrawSelected,
    onSetDrawSelected,
    onSetDrawSelectedAll,
    onRemoveDrawSelectedAll,
    onSetDrawSelectedList,
    onSetTicketPriceDefault,
    onSetDrawMapByDate,
    onSetDrawingConfig,
    onSetTicketOrder,
    onResetTicketOrderNumber,
    onInitNumbers,
    onSetNumbers,
    onInitSpots,
    onSetSpots,
    onSetSpotSelected,
    onSetSpotDefault,
    onSetTicketSessionSelected,
    onResetTicketSession,
    onRandomNumberTicket,
    onUpdateTicketOrderNumber,
    onAddTicket,
    onRemoveTicket,
    onClearNumberTicket,
    onSetTicketSession,
    onUpdateSessionItem,
    onRemoveSessionItem,
    onClearNumberSessionItem,
    onMergeTicketOrderFromSession,
    onFetchConfig,
    onGetConfig,
    onSetNumberChoiceModal,
    onCreateOrder,
    onCreateOrderLoading
} = kenoGameSlice.actions

export const kenoGameReducer = kenoGameSlice.reducer
