export const RequestMethods = {
    GET_BALANCES: 'getBalances',
    ALLOCATE_IF_ABSENT: 'allocateIfAbsent',
    GET_BALANCE: 'getBalance',
    GET_OWNER_BALANCE: 'getOwnerBalance',
    FREEZE_BALANCE: 'freezeBalance',
    UNFREEZE_BALANCE: 'unfreezeBalance',
    DEDUCT_BALANCE: 'deductBalance',
    CREDIT_BALANCE: 'creditBalance',
    CREDIT_BALANCE_BATCH: 'creditBalanceBatch',
    GET_TOKEN: 'getToken',
    GET_ALL_TOKENS: 'getAllTokens',
    GET_CURRENCY_CONFIG: 'getCurrencyConfig',
    GET_WALLET_CONFIG: 'getWalletConfig',
    FIND_TOKENS_BY_FILTERS: 'findTokensByFilters',
    INIT_BALANCE: 'initBalance',
    GET_DEPOSIT_ADDRESSES: 'getDepositAddresses',
    FIND_TRANSACTIONS_BY_FILTERS: 'findTransactionsByFilters',
    FIRST_TRANSACTION_BY_FILTERS: 'firstTransactionByFilters',
    CREATE_WITHDRAW_TRANSACTION: 'createWithdrawTransaction',
    UPDATE_WITHDRAW_TRANSACTION_STATUS: 'updateWithdrawTransactionStatus'
}
