export const MESSAGE_BROKER_ID = {
    PORTAL_WALLET: 'PORTAL_WALLET',
    PORTAL_DEPOSIT_NOTIFICATION: 'PORTAL_DEPOSIT_NOTIFICATION',
    PORTAL_WITHDRAWAL_NOTIFICATION: 'PORTAL_WITHDRAWAL_NOTIFICATION',
    GAME_DICE_BALANCE_CHANGE_NOTIFICATION: 'GAME_DICE_BALANCE_CHANGE_NOTIFICATION',
    PORTAL_GAME_SESSION_MODAL: 'PORTAL_GAME_SESSION_MODAL',
    PORTAL_MAX_ACTIVE_CONNECTION_MODAL: 'PORTAL_MAX_ACTIVE_CONNECTION_MODAL'
}
