export const PROVIDER_LOGIN = {
    INTERNAL: 'INTERNAL',
    FACEBOOK: 'FACEBOOK',
    GOOGLE: 'GOOGLE',
    APPLE: 'APPLE',
    META_MASK: 'META_MASK',
    BINANCE_CHAIN_WALLET: 'BINANCE_CHAIN_WALLET',
    TRON_LINK: 'TRON_LINK',
    GUEST: 'GUEST'
}
