export namespace Router {
    export const ROUTER_HOME = '/'
    export const ROUTER_WALLET = '/wallet'
    export const ROUTER_ORDER = '/order'
    export const ROUTER_PURCHASED_ORDER = '/purchased'
    export const ROUTER_CANCELED_ORDER = '/canceled'
    export const ROUTER_GAME = '/games'
    export const ROUTER_GAME_DETAIL = '/games/[slug]'
    export const ROUTER_GAME_CLASSIC = '/games/classic-game'
    export const ROUTER_HIGH_FREQUENCY_GAME = '/high-frequency'
    export const ROUTER_INSTANTS_GAME = '/instants'
    export const ROUTER_CLASSIC_GAME = '/classic-game'
    export const ROUTER_CART = '/cart'
    export const ROUTER_PAYMENT = '/payment'
    export const ROUTER_PROFILE = '/profile'
    export const ROUTER_TFA = '/two-factor-authentication'
    export const ROUTER_DWA = '/default-withdrawal-address'
    export const ROUTER_UP = '/update-password'
    export const ROUTER_UEA = '/update-email'
}
