website-build-service-in-merge-request:
    extends: .build-service
    variables:
        PACKAGE_SERVICE: web
    rules:
        - if: $CI_PIPELINE_SOURCE == "merge_request_event" && $CI_MERGE_REQUEST_TARGET_BRANCH_NAME =~ /^dev/
          changes:
              - 'apps/web/**/*'
    artifacts:
        paths:
            - ''

website-build-service:
    extends: .build-service
    variables:
        PACKAGE_SERVICE: web
    rules:
        - if: $CI_COMMIT_BRANCH =~ /^dev/
          changes:
              - 'apps/web/**/*'

website-publish-cdn:
    extends: .publish-cdn
    variables:
        PACKAGE_SERVICE: web
        PACKAGE_SERVICE_DIR: $CI_PROJECT_DIR/apps/$PACKAGE_SERVICE
        GSUTIL_URI: gs://athena-lottery-dev
    rules:
        - if: $CI_COMMIT_TAG =~ /^v/
          changes:
              - 'apps/web/**/*'
        - if: $CI_COMMIT_BRANCH =~ /^dev/
          changes:
              - 'apps/web/**/*'
    needs:
        - website-build-service

website-package-image:
    extends: .package-image
    variables:
        PACKAGE_SERVICE: web
        PACKAGE_SERVICE_DIR: $CI_PROJECT_DIR/apps/$PACKAGE_SERVICE
        CI_REGISTRY_IMAGE: $GCP_REGISTRY_HOST/$CI_PROJECT_NAME-$PACKAGE_SERVICE
    rules:
        - if: $CI_COMMIT_TAG =~ /^v/
          changes:
              - 'apps/web/**/*'
        - if: $CI_COMMIT_BRANCH =~ /^dev/
          changes:
              - 'apps/web/**/*'
    needs:
        - website-build-service

website-deploy:
    extends: .deploy
    variables:
        PACKAGE_SERVICE: web
        CLOUD_RUN_SERVICE_NAME: lottery-$DEPLOY_ENVIRONMENT
        CI_REGISTRY_IMAGE: $GCP_REGISTRY_HOST/$CI_PROJECT_NAME-$PACKAGE_SERVICE
    rules:
        - if: $CI_COMMIT_TAG =~ /^v/
          changes:
              - 'apps/web/**/*'
        - if: $CI_COMMIT_BRANCH =~ /^dev/
          changes:
              - 'apps/web/**/*'
    needs:
        - website-package-image
