import { MB } from '@lottery/utils'

export enum MessageBrokerKey {
    FETCH_AVAILABLE_BALANCE = MB.TYPE_CONVENTION.KENO + 1,
    INSTANT_KENO_CREATE_NEW_TURN = MB.TYPE_CONVENTION.KENO + 2,
    INSTANT_KENO_PLACE_BET_RESULT = MB.TYPE_CONVENTION.KENO + 3,
    INSTANT_KENO_PLACE_BET_FROM_DELAY_RESULT = MB.TYPE_CONVENTION.KENO + 4,
    INSTANT_KENO_GET_BET_RESULTS = MB.TYPE_CONVENTION.KENO + 5,
    INSTANT_KENO_GET_LAST_RESULTS = MB.TYPE_CONVENTION.KENO + 6,
    INSTANT_KENO_GET_BET_INFO = MB.TYPE_CONVENTION.KENO + 7,
    INSTANT_KENO_BET_RESULT_NOTIFICATION = MB.TYPE_CONVENTION.KENO + 8,
    INSTANT_KENO_GET_BET_RESULT_FAIRNESS = MB.TYPE_CONVENTION.KENO + 9,
    INSTANT_KENO_PLACE_BET_ERROR = MB.TYPE_CONVENTION.KENO + 10,
    INSTANT_KENO_PAUSE_AUTO_BET = MB.TYPE_CONVENTION.KENO + 11
}

export enum MessageBrokerID {
    INSTANT_KENO_CHECK_FAIRNESS,
    INSTANT_KENO_GAME_BOARD,
    INSTANT_KENO_TABLE_RESULT,
    INSTANT_KENO_LAST_BET,
    INSTANT_KENO_BET_DETAIL,
    INSTANT_KENO_GAME,
    INSTANT_KENO_BOARD_CENTER,
    INSTANT_KENO_JACKPOTS
}

export enum GameStatePlay {
    WIN = 1,
    LOSS,
    INIT
}

export enum RareType {
    RESET,
    INCREASE
}

export enum AutoPlayStatus {
    BALANCE_NOT_ENOUGH = 1,
    MAXIMUM_NUMBER_OF_BET,
    STOP_ON_PROFIT,
    STOP_ON_LOSS,
    NEW_TURN
}

export enum ResultTabConfig {
    ALL_BET,
    MY_BET,
    HIGH_ROLLER,
    RARE_WIN
}
