import { MB } from '@lottery/utils'

export enum MessageBrokerKey {
    FETCH_AVAILABLE_BALANCE = MB.TYPE_CONVENTION.LIMBO + 1,
    LIMBO_CREATE_NEW_TURN = MB.TYPE_CONVENTION.LIMBO + 2,
    LIMBO_PLACE_BET_RESULT = MB.TYPE_CONVENTION.LIMBO + 3,
    LIMBO_PLACE_BET_FROM_DELAY_RESULT = MB.TYPE_CONVENTION.LIMBO + 4,
    LIMBO_GET_BET_RESULTS = MB.TYPE_CONVENTION.LIMBO + 5,
    LIMBO_GET_LAST_RESULTS = MB.TYPE_CONVENTION.LIMBO + 6,
    LIMBO_GET_BET_INFO = MB.TYPE_CONVENTION.LIMBO + 7,
    LIMBO_BET_RESULT_NOTIFICATION = MB.TYPE_CONVENTION.LIMBO + 8,
    LIMBO_GET_BET_RESULT_FAIRNESS = MB.TYPE_CONVENTION.LIMBO + 9,
    LIMBO_PLACE_BET_ERROR = MB.TYPE_CONVENTION.LIMBO + 10,
    LIMBO_PAUSE_AUTO_BET = MB.TYPE_CONVENTION.LIMBO + 11
}

export enum MessageBrokerID {
    LIMBO_CHECK_FAIRNESS,
    LIMBO_GAME_BOARD,
    LIMBO_TABLE_RESULT,
    LIMBO_LAST_BET,
    LIMBO_BET_DETAIL,
    LIMBO_GAME,
    LIMBO_BOARD_CENTER,
    LIMBO_JACKPOTS
}

export enum GameStatePlay {
    WIN = 1,
    LOSS,
    INIT
}

export enum RareType {
    RESET,
    INCREASE
}

export enum AutoPlayStatus {
    BALANCE_NOT_ENOUGH = 1,
    MAXIMUM_NUMBER_OF_BET,
    STOP_ON_PROFIT,
    STOP_ON_LOSS,
    NEW_TURN
}

export enum ResultTabConfig {
    ALL_BET,
    MY_BET,
    HIGH_ROLLER,
    RARE_WIN
}
